branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 protocol changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: [version]
          from: ^.+$
          to: ${nextRelease.version}
          countMatches: true
          results:
            - file: version
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: |
        make release-assets
  - - "@semantic-release/github"
    - assets:
        - name: okp4d-${nextRelease.version}-linux-amd64
          label: okp4d-${nextRelease.version}-linux-amd64
          path: "./target/release/okp4d-${nextRelease.version}-linux-amd64"
        - name: okp4d-${nextRelease.version}-linux-amd64.tar.gz
          label: okp4d-${nextRelease.version}-linux-amd64.tar.gz
          path: "./target/release/okp4d-${nextRelease.version}-linux-amd64.tar.gz"
        - name: okp4d-${nextRelease.version}-linux-arm64
          label: okp4d-${nextRelease.version}-linux-arm64
          path: "./target/release/okp4d-${nextRelease.version}-linux-arm64"
        - name: okp4d-${nextRelease.version}-linux-arm64.tar.gz
          label: okp4d-${nextRelease.version}-linux-arm64.tar.gz
          path: "./target/release/okp4d-${nextRelease.version}-linux-arm64.tar.gz"
        - name: sha256sum.txt
          label: sha256sum.txt
          path: "./target/release/sha256sum.txt"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version
      message: "chore(release): perform release ${nextRelease.version}"
