accounts:
  - name: alice
    coins: [ "100know" ]
  - name: bob
    coins: [ "50know" ]
  - name: dao
    coins: [ "10000000000know" ]
  - name: validator
    coins: [ "1000001know" ]
validator:
  name: validator
  staked: "1000000know"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: dao
  coins_max: [ "1000know" ]
  coins: [ "100know" ]
genesis:
  chain_id: "okp4-localnet-1"
  app_state:
    staking:
      params:
        bond_denom: "know"
