name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-proto:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: "1.19"

      - name: Build proto
        run: |
          make build-proto

  generate-proto:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: "1.19"

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1

      - name: Generate proto
        run: |
          make generate-proto

  build-go:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: "1.19"

      - name: Build go project
        run: |
          make build

  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build .
